#cloud-config

coreos:
  update:
    group: alpha
    reboot-strategy: off

  etcd:
    addr: $public_ipv4:4001
    peer-addr: $public_ipv4:7001

  units:
    - name: update-engine.service
      command: stop
      mask: true

    - name: etcd.service
      command: start
