#cloud-config

coreos:
  update:
    group: alpha
    reboot-strategy: off

  etcd:
    discovery: http://%discovery_ip_addr%:4001/v2/keys/cluster
    addr: $public_ipv4:4001
    peer-addr: $public_ipv4:7001

  units:
    - name: update-engine.service
      command: stop
      mask: true

    - name: etcd.service
      command: start

    - name: flanneld.service
      command: start
      content: |
        [Unit]
        Requires=etcd.service
        After=etcd.service

        [Service]
        ExecStartPre=-/usr/bin/etcdctl set /coreos.com/network/config '{"Network":"10.100.0.0/16"}'
        ExecStart=/opt/bin/flanneld -ip-masq=true -iface=$public_ipv4
        Restart=always
        RestartSec=5

        [Install]
        WantedBy=multi-user.target

    - name: use-flannel.service
      command: start
      content: |
        [Unit]
        ConditionPathExists=/etc/systemd/system/docker.service.d/10-flannel.conf.init
        Description=Use Flannel for Docker networking
        After=flanneld.service

        [Service]
        Type=oneshot
        ExecStart=/usr/bin/systemctl stop docker
        ExecStart=/usr/bin/mv /etc/systemd/system/docker.service.d/10-flannel.conf.init /etc/systemd/system/docker.service.d/10-flannel.conf
        ExecStart=/usr/bin/systemctl daemon-reload

        [Install]
        WantedBy=multi-user.target

    - name: apiserver.service
      command: start
      content: |
        [Unit]
        Description=Kubernetes API Server
        Documentation=https://github.com/GoogleCloudPlatform/kubernetes
        After=etcd.service
        After=docker.service
        Wants=etcd.service
        Wants=docker.service

        [Service]
        ExecStart=/opt/bin/apiserver \
        -address=127.0.0.1 \
        -port=8080 \
        -etcd_servers=http://127.0.0.1:4001 \
        -machines=%minion_ip_addrs% \
        -portal_net=10.101.0.0/16
        Restart=always
        RestartSec=5

        [Install]
        WantedBy=multi-user.target

    - name: controller-manager.service
      command: start
      content: |
        [Unit]
        Description=Kubernetes Controller Manager
        Documentation=https://github.com/GoogleCloudPlatform/kubernetes
        After=etcd.service
        After=docker.service
        Wants=etcd.service
        Wants=docker.service

        [Service]
        ExecStart=/opt/bin/controller-manager -master=127.0.0.1:8080
        Restart=always
        RestartSec=5

        [Install]
        WantedBy=multi-user.target

    - name: scheduler.service
      command: start
      content: |
        [Unit]
        Description=Kubernetes Scheduler
        Documentation=https://github.com/GoogleCloudPlatform/kubernetes
        After=etcd.service
        After=docker.service
        Wants=etcd.service
        Wants=docker.service

        [Service]
        ExecStart=/opt/bin/scheduler -master=127.0.0.1:8080
        Restart=always
        RestartSec=5

        [Install]
        WantedBy=multi-user.target

write_files:
  - path: /etc/systemd/system/docker.service.d/10-flannel.conf.init
    permissions: 0644
    owner: root
    content: |
      [Unit]
      Requires=flanneld.service
      After=flanneld.service

      [Service]
      EnvironmentFile=/run/flannel/subnet.env
      ExecStartPre=/bin/bash -c "/usr/bin/ifconfig docker0 down || true"
      ExecStartPre=/bin/bash -c "/usr/sbin/brctl delbr docker0 || true"
      ExecStart=
      ExecStart=/usr/bin/docker --daemon --storage-driver=btrfs --host=fd:// --bip=${FLANNEL_SUBNET} --mtu=${FLANNEL_MTU}
      Restart=always
      RestartSec=5
