#cloud-config

coreos:
  update:
    group: alpha
    reboot-strategy: off
  etcd:
    discovery: http://%discovery_ip_addr%:4001/v2/keys/cluster
    addr: $public_ipv4:4001
    peer-addr: $public_ipv4:7001

  units:
    - name: update-engine.service
      command: stop
      mask: true

    - name: etcd.service
      command: start

    - name: fleet.service
      command: start
      runtime: no
      content: |
        [Unit]
        Description=fleet

        [Service]
        Environment=FLEET_PUBLIC_IP=$public_ipv4
        ExecStart=/usr/bin/fleet

    - name: flanneld.service
      command: start
      content: |
        [Unit]
        Requires=etcd.service
        After=etcd.service

        [Service]
        ExecStart=/opt/bin/flanneld -iface=$public_ipv4
        Restart=always
        RestartSec=5

        [Install]
        WantedBy=multi-user.target

    - name: docker.service
      command: restart
      content: |
        [Unit]
        Description=Docker Application Container Engine
        Documentation=http://docs.docker.io
        Requires=flanneld.service
        After=flanneld.service
        After=network.target

        [Service]
        # Defaults
        Environment="TMPDIR=/var/tmp/"
        ExecStartPre=/bin/mount --make-rprivate /
        LimitNOFILE=1048576
        LimitNPROC=1048576
        # Flannel
        EnvironmentFile=/run/flannel/subnet.env
        ExecStartPre=-/usr/bin/ip link set dev docker0 down
        ExecStartPre=-/usr/sbin/brctl delbr docker0
        # Run docker but don't have docker automatically restart
        # containers. This is a job for systemd and unit files.
        ExecStart=/usr/bin/docker --daemon --storage-driver=btrfs --host=fd:// --bip=${FLANNEL_SUBNET} --mtu=${FLANNEL_MTU}
        Restart=always
        RestartSec=5

        [Install]
        WantedBy=multi-user.target

    - name: kubelet.service
      command: start
      content: |
        [Unit]
        Description=Kubernetes Kubelet
        Documentation=https://github.com/GoogleCloudPlatform/kubernetes
        After=etcd.service
        After=docker.service
        Wants=etcd.service
        Wants=docker.service

        [Service]
        ExecStart=/opt/bin/kubelet \
        -address=0.0.0.0 \
        -port=10250 \
        -hostname_override=$public_ipv4 \
        -etcd_servers=http://127.0.0.1:4001
        Restart=always
        RestartSec=5

        [Install]
        WantedBy=multi-user.target

    - name: proxy.service
      command: start
      content: |
        [Unit]
        Description=Kubernetes Proxy
        Documentation=https://github.com/GoogleCloudPlatform/kubernetes
        After=etcd.service
        After=docker.service
        Wants=etcd.service
        Wants=docker.service

        [Service]
        ExecStart=/opt/bin/proxy -etcd_servers=http://127.0.0.1:4001
        Restart=always
        RestartSec=5

        [Install]
        WantedBy=multi-user.target
