#cloud-config

coreos:
  update:
    group: alpha
    reboot-strategy: off

  etcd:
    discovery: http://%discovery_ip_addr%:4001/v2/keys/cluster
    addr: $public_ipv4:4001
    peer-addr: $public_ipv4:7001

  units:
    - name: update-engine.service
      command: stop
      mask: true

    - name: etcd.service
      command: start

    - name: fleet.service
      command: start
      runtime: no
      content: |
        [Unit]
        Description=fleet

        [Service]
        Environment=FLEET_PUBLIC_IP=$public_ipv4
        ExecStart=/usr/bin/fleet

    - name: flanneld.service
      command: start
      content: |
        [Unit]
        Requires=etcd.service
        After=etcd.service

        [Service]
        ExecStart=/opt/bin/flanneld -ip-masq=true -iface=$public_ipv4
        Restart=always
        RestartSec=5

        [Install]
        WantedBy=multi-user.target

    - name: use-flannel.service
      command: start
      content: |
        [Unit]
        ConditionPathExists=/etc/systemd/system/docker.service.d/10-flannel.conf.init
        Description=Use Flannel for Docker networking
        After=flanneld.service

        [Service]
        Type=oneshot
        ExecStart=/usr/bin/systemctl stop docker
        ExecStart=/usr/bin/mv /etc/systemd/system/docker.service.d/10-flannel.conf.init /etc/systemd/system/docker.service.d/10-flannel.conf
        ExecStart=/usr/bin/systemctl daemon-reload

        [Install]
        WantedBy=multi-user.target

    - name: kubelet.service
      command: start
      content: |
        [Unit]
        Description=Kubernetes Kubelet
        Documentation=https://github.com/GoogleCloudPlatform/kubernetes
        After=etcd.service
        After=docker.service
        Wants=etcd.service
        Wants=docker.service

        [Service]
        ExecStart=/opt/bin/kubelet \
        -address=0.0.0.0 \
        -port=10250 \
        -hostname_override=$public_ipv4 \
        -etcd_servers=http://127.0.0.1:4001
        Restart=always
        RestartSec=5

        [Install]
        WantedBy=multi-user.target

    - name: proxy.service
      command: start
      content: |
        [Unit]
        Description=Kubernetes Proxy
        Documentation=https://github.com/GoogleCloudPlatform/kubernetes
        After=etcd.service
        After=docker.service
        Wants=etcd.service
        Wants=docker.service

        [Service]
        ExecStart=/opt/bin/proxy -etcd_servers=http://127.0.0.1:4001
        Restart=always
        RestartSec=5

        [Install]
        WantedBy=multi-user.target

write_files:
  - path: /etc/systemd/system/docker.service.d/10-flannel.conf.init
    permissions: 0644
    owner: root
    content: |
      [Unit]
      Requires=flanneld.service
      After=flanneld.service

      [Service]
      EnvironmentFile=-/run/flannel/subnet.env
      ExecStartPre=/bin/bash -c "/usr/bin/ifconfig docker0 down || true"
      ExecStartPre=/bin/bash -c "/usr/sbin/brctl delbr docker0 || true"
      ExecStart=
      ExecStart=/usr/bin/docker --daemon --storage-driver=btrfs --host=fd:// --bip=${FLANNEL_SUBNET} --mtu=${FLANNEL_MTU}
      Restart=always
      RestartSec=5
